version: "3.8"

services:
  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: mysql-8.0
    ports:
      - 3306:3306
    volumes:
      - ./conf/conf.d:/etc/mysql/conf.d
      - ./conf/initdb.d:/docker-entrypoint-initdb.d
      - ./conf/data:/var/lib/mysql
    # env_file: .env
    command:
      - --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: node-complete
      TZ: Asia/Seoul
  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
